
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env

  app:
    build: .
    container_name: springboot_container
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  pgdata:
